import { Router } from "express";
import { getAllTutors, getUserDetails, toggleBlockUser } from "./admin.controller";
import { authenticate } from "../../middlewares/auth.middleware";
import { getAllCourses } from "../courses/course.controller";
const adminRoutes= Router();
adminRoutes.get("/Users",authenticate ,getAllTutors);
adminRoutes.get(  "/courses",  authenticate, getAllCourses);
adminRoutes.patch("/users/:id/block", authenticate, toggleBlockUser);
adminRoutes.get("/users/:id/details",authenticate, getUserDetails);
export default adminRoutes;